name: Build bar

on:
  workflow_dispatch:
    inputs:
      first:
        description: first thing
        required: true
        type: string

      second:
        description: second thing
        required: true
        type: string

      reason:
        description: reason from the parent run
        required: false
        type: string

run-name: ${{ inputs.reason || format('{0}-{1}', inputs.first, inputs.second) }}

jobs:

  do-one-thing:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        if: ${{ inputs.reason }}
        env:
          caller: ${{ inputs.reason }}
        run: |
          (
            caller=${caller%%:*}
            echo "## Caller"
            echo
            echo "[$caller](https://github.com/tureba/wtest/actions/runs/$caller)"
            echo
          ) >> $GITHUB_STEP_SUMMARY

      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)

      - shell: bash
        run: |
          echo "got first: ${{ inputs.first }}"
          echo "got second: ${{ inputs.second }}"
          echo "got reason: ${{ inputs.reason }}"
          # add random fail. around 1/32th of the time
          [ $((RANDOM)) -gt 1000 ]
