name: Build bar

on:
  workflow_dispatch:
    inputs:
      first:
        description: first thing
        required: true
        type: string

      second:
        description: second thing
        required: true
        type: string

      reason:
        description: reason from the parent run
        required: false
        type: string

run-name: ${{ inputs.reason || format('{0}-{1}', inputs.first, inputs.second) }}

jobs:

  do-one-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        if: ${{ inputs.reason }}
        id: run
        with:
          script: |
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.inputs.reason.match("^[0-9]+")[0],
            });
            console.log(run);
            return run;

      - shell: bash
        if: ${{ inputs.reason }}
        env:
          caller: ${{ steps.run.outputs.result }}
        run: |
          (
            echo
            jq -r '.[]|("# [" + (.name | sub("^[0-9]+: ";"")) + "](" + .html_url + ")")' <<<"${caller}"
            echo
          ) >> "${GITHUB_STEP_SUMMARY}"

      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)

      - shell: bash
        run: |
          echo "got first: ${{ inputs.first }}"
          echo "got second: ${{ inputs.second }}"
          echo "got reason: ${{ inputs.reason }}"
          echo "got secret: ${{ secrets.yes }}"
          # add random fail. around 1/32th of the time
          [ $((RANDOM)) -gt 1000 ]
