name: Build bar

on:
  workflow_dispatch:
    inputs:
      id:
        description: id of the thing
        required: true
        type: string

      parent:
        description: id of the parent run
        required: true
        type: string

run-name: ${{ inputs.id }}

jobs:

  do-one-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)

      - shell: bash
        run: |
          echo "got id: ${{ inputs.id }}"
          echo "got parent: ${{ inputs.parent }}"
          # add random fail. around 1/32th of the time
          [ $((RANDOM)) -gt 1000 ]
