name: Build all

on:

  workflow_dispatch:
    inputs:
      foo:
        description: foo input
        required: true
        default: ALL
        type: choice
        options:
          - ALL
          - abc
          - def
          - ghi

      bar:
        description: bar input
        required: true
        default: ALL
        type: choice
        options:
          - ALL
          - x
          - y
          - z

defaults:
  run:
    shell: bash

jobs:

  print-inputs:
    runs-on: ubuntu-latest
    steps:

      - env:
          var: ${{ toJson(github.event) }}
        run: |
          echo "github.event: ${var}"

      - env:
          var: ${{ toJson(inputs) }}
        run: |
          echo "inputs: ${var}"

      - env:
          var: ${{ toJson(github.on) }}
        run: |
          echo "github.on: ${var}"

      - env:
          var: ${{ toJson(github.on.workflow_call) }}
        run: |
          echo "github.on.workflow_call: ${var}"

      - env:
          var: ${{ toJson(github.inputs) }}
        run: |
          echo "github.inputs: ${var}"

      - env:
          var: ${{ toJson(github.event.inputs) }}
        run: |
          echo "github.event.inputs: ${var}"

      - env:
          var: ${{ toJson(inputs.foo.options) }}
        run: |
          echo "inputs.foo.options: ${var}"

  validate-inputs:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ ! contains(fromJson('["ALL","abc","def","ghi"]'), inputs.foo) }}
        env:
          foo: ${{ inputs.foo }}
        run: |
          echo "::error::${foo} is not valid for foo"
          return 1
      - if: ${{ ! contains(fromJson('["ALL","x","y","z"]'), inputs.bar) }}
        env:
          bar: ${{ inputs.bar }}
        run: |
          echo "::error::${bar} is not valid for bar"
          return 1

  do-all-things:
    needs: validate-inputs
    strategy:
      matrix:
        foo: ${{ (inputs.foo == 'ALL') && fromJson('["abc","def","ghi"]') || fromJson(format('["{0}"]', inputs.foo)) }}
        bar: ${{ (inputs.bar == 'ALL') && fromJson('["x","y","z"]') || fromJson(format('["{0}"]', inputs.bar)) }}
      fail-fast: false
      max-parallel: 1
    uses: tureba/wtest/.github/workflows/build-one.yml@main
    with:
      foo: ${{ matrix.foo }}
      bar: ${{ matrix.bar }}
