name: Build foo

on:
  workflow_dispatch:
    inputs:
      first:
        description: first input
        required: true
        type: string

      second:
        description: second input
        required: true
        type: string

run-name: ${{ format('Building with first={0} and second={1}', inputs.first, inputs.second) }}

jobs:

  do-one-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Build bar',
              ref: context.ref,
              inputs: { first: ${{ inputs.first }}, second: ${{ inputs.second }} },
              });

