name: Build foo

on:
  workflow_dispatch:
    inputs:
      first:
        description: first input
        required: true
        type: string

      second:
        description: second input
        required: true
        type: string

run-name: ${{ format('Building with first={0} and second={1}', inputs.first, inputs.second) }}

jobs:

  do-one-thing:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'bar.yml',
              ref: context.ref,
              inputs: context.payload.inputs,
              });

      - uses: actions/github-script@v6
        with:
          script: |
            const iterator = github.paginate.iterator(github.rest.actions.listWorkflowRuns, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'bar.yml',
              });

            // iterate through each response
            for await (const { data: runs } of iterator) {
              for (const run of runs) {
                console.log(run);
              }
            }
