name: Test envs

on:
  workflow_dispatch:

env:
  foo: one

jobs:
  do-one-thing:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "got foo: ${{ env.foo }}"
  do-other-thing:
    uses: tureba/wtest/.github/workflows/test-env-inner.yml@main
